### ISSUE TITLE
Can you provide samples on @jsplumb/browser-ui-lists. I am unable to use addList method of jsplumb instance in typescript. jtk-scrollable-list attribute also seems to not work. 

### ISSUE THREAD

**Issue by anusha2597** [jsplumb/jsplumb#1060]

**Comment by sporritt** [comment]
there's a demo here

https://github.com/jsplumb-demonstrations/scrollable-lists/tree/main/ts

it's still setup to use 4.0.0 but 5.0.0 is not different in any major way

**Comment by anusha2597** [comment]
It's working in version 4.0.0. But, I am using  5.0.0RC1 version. 
I am getting the following error in this.
 'addList' does not exist on type 'BrowserJsPlumbInstance'.

**Comment by sporritt** [comment]
hmm yeah, i guess i should update that.

you could have a look in the unit tests:

https://github.com/jsplumb/jsplumb/blob/master/tests/lists/tests.js

a list manager is instantiated in the setup method:

https://github.com/jsplumb/jsplumb/blob/master/tests/lists/tests.js#L84

**Comment by sporritt** [comment]
(one key piece being you have to import the package `@jsplumb/browser-ui-=ists`.

**Comment by anusha2597** [comment]
I have one more doubt. Can we add jtk-scrollable-list to mat-tree as I want the connections on tree nodes to be scrolled when the tree is scrolled in angular.

**Comment by sporritt** [comment]
I don't know. You'll have to try this to see.

**Comment by anusha2597** [comment]
I have tried it but its not working.

**Comment by sporritt** [comment]
aha! and so the answer would appear to be, no.  um.
